### ISSUE TITLE
HostedZone might be different from the domain name.

### ISSUE THREAD

**Issue by cnnblike** [seeebiii/ses-verify-identities#132]
Hi,
https://github.com/seeebiii/ses-verify-identities/blob/main/src/verify-ses-domain.ts#L109-L113 this contains a bug.
HostedZone might be different from the domain name.
Let's assume we have a hosed zone named with (example.com), it's highly possible that user may use (aws.example.com) to send out mail.
this package: https://github.com/mooyoul/aws-cdk-ses-domain-identity/blob/master/src/dns-validated-domain-identity.ts#L16-L28 use two separate parameter to make it slightly more configurable.
KL

**Comment by seeebiii** [comment]
@mthenw Sure! I don't have enough time right now to do this but if anyone wants to implement a solution, feel free and I'll merge it :)

**Comment by cnnblike** [comment]
PR created on https://github.com/seeebiii/ses-verify-identities/pull/195, feel free to comment.
