### ISSUE TITLE
add DeletionPolicy

### ISSUE THREAD

**Issue by Nemo64** [seeebiii/ses-verify-identities#205]
Hi,

This is an awesome little library.

It would be awesome if I could define the deletion policy of an email identity as I don't really want it deleted after i remove the stack.
The api call does not seem to care that the identity already exists, so there is no collision in creating it multiple times.

**Comment by seeebiii** [comment]
Hi @Nemo64 , sounds like a good addition! I'm happy to receive contributions if you have time because I don't have much time at the moment...
