### ISSUE TITLE
CDK v2 support

### ISSUE THREAD

**Issue by ahammond** [seeebiii/ses-verify-identities#503]
I'd love to use this. Is there any plan for supporting CDK v2?

**Comment by seeebiii** [comment]
Not yet, haven't updated this project in the past months.. But I can try to find some time this week and update it ;)

**Comment by o-alexandrov** [comment]
I upgraded the code in this repo and used it directly in projects, the attached converted files might save you some time
- [ses-verify-identities.zip](https://github.com/seeebiii/ses-verify-identities/files/7577182/ses-verify-identities.zip)

**Comment by ahammond** [comment]
@o-alexandrov I did something similar. Forward ported to CDKv2 and just dumped it in the app that's using it. Gross, but sufficient until there's a better solution. :)

@seeebiii great library, btw.

**Comment by ahammond** [comment]
Not stale
