### ISSUE TITLE
User VerifyDomainDkim

### ISSUE THREAD

**Issue by jasonwadsworth** [seeebiii/ses-verify-identities#509]
Instead of TXT records the new standard is to use the `VerifyDomainDkim` API, which returns values that are used to create CNAME records. Documentation for the API is [here](https://docs.aws.amazon.com/ses/latest/APIReference/API_VerifyDomainDkim.html)

**Comment by seeebiii** [comment]
@jasonwadsworth sorry for my late response - I'm not actively developing this construct, just from time to time. I just wanted to let you know that for domains, I'm already using the `VerifyDomainDkim` API. See [here](https://github.com/seeebiii/ses-verify-identities/blob/main/src/verify-ses-domain.ts#L146) and the lines below where I also use the response to add CNAME records. If there's anything else in that direction which I can improve, I'm happy to hear it but so far it looks like I'm doing it already as you suggested.
